### ISSUE TITLE
[ reactiveTransform() ]Operater should not being apllied to porperties that deconstructed from reactiveTransform()

### ISSUE THREAD

**Issue by polarove** [vueuse/motion#106]
const { state, transform } = reactiveTransform({
  rotateX: 0,
  rotateY: 0,
})
const rotate = (e: any) => {

  // Typescript alarms here
  // Operator '+=' cannot be applied to types 'string | number' and 'number'
  state.rotateX += 0.1
  state.rotateY += 0.1

}

**Comment by Ryuuki6602** [comment]
It's a type error, which means it functions still.
