### ISSUE TITLE
Fade is not working

### ISSUE THREAD

**Issue by Luizboaventura1** [vueuse/motion#150]
When you go to another page and come back, the fade doesn't work and the element is hidden, I'm using nuxt 3

**Comment by BobbieGoede** [comment]
This issue is likely fixed by #171 which is now included in the latest release v2.1.0, but without a reproduction I'm unable to confirm this, can you check if this issue has been resolved after installing the latest version?

**Comment by Luizboaventura1** [comment]
I updated and now it works correctly
