### ISSUE TITLE
Elements won't appear.

### ISSUE THREAD

**Issue by robertlocskai** [vueuse/motion#153]
Hey guys, I'm using vueuse motion default preset animations. 

My problem is, if I load the page and there are elements already that have the animation property added they won't appear.
Only if I scroll down and back up.

I'm using the "v-motion-slide-visible-left".

Thanks for any help in advance!

**Comment by rylanharper** [comment]
See my solution [here](https://github.com/vueuse/motion/issues/143#issuecomment-1693953550)

**Comment by khalednadam** [comment]
@rylanharper does your temporary solution work on visible and once visible ?

**Comment by rylanharper** [comment]
@khalednadam yes it does!:)
