### ISSUE TITLE
visible-once / visibleOnce Documentation (Directive Usage)

### ISSUE THREAD

**Issue by fabianbeier** [vueuse/motion#154]
I had the problem that the element that i applied `:visible-once="…` to was not animating (Directive Usage). After reading some Issues here i tried to write `:visibleOnce="…` and it **worked**!

In the Docs it only states the kebab-case (visible-once). Is the camel-case the correct Version? If so I think it needs to be updated in the Docs.

**Comment by brambekkers** [comment]
Thanks for your comment. My eslint is always complaining about this not being hyphenated. Is there a possibility to make it work with visible-once?
