### ISSUE TITLE
The nuxt plugin is missing motion.d.ts

### ISSUE THREAD

**Issue by KeJunMao** [vueuse/motion#155]
![image](https://github.com/vueuse/motion/assets/18414281/1ec3ff9d-8993-4d67-b35f-82ac92e7df8b)

**Comment by reslear** [comment]
hi @Tahul this is breaks nuxt types for `useNuxtApp()`

proof:

`.nuxt/types/plugins.d.ts`

<img width="571" alt="Screenshot 2023-11-03 at 17 52 45" src="https://github.com/vueuse/motion/assets/12596485/7ec7a45b-d63d-49ac-b4d8-beeb003f2e3f">

temp solution: 

`pnpm patch @vueuse/motion`

```diff
diff --git a/dist/runtime/templates/motion.d.ts b/dist/runtime/templates/motion.d.ts
new file mode 100644
index 0000000000000000000000000000000000000000..9cf58a7924cd41b6078876411e90490dc1c0a5e7
--- /dev/null
+++ b/dist/runtime/templates/motion.d.ts
@@ -0,0 +1,2 @@
+declare const _default: any;
+export default _default;
```

**Comment by reslear** [comment]
strange but I found this PR https://github.com/vueuse/motion/pull/136
