### ISSUE TITLE
I've got a horizontal scroll with v-motion-slide-visible-once-right

### ISSUE THREAD

**Issue by thomasbnt** [vueuse/motion#159]
Hello, when I put `v-motion-slide-visible-once-right` on my code with Nuxt v3, I've got a horizontal scroll. 
I followed the [process to include motion](https://motion.vueuse.org/getting-started/nuxt/) on my project. Animations works, but create this bug.

**Comment by tony1c** [comment]
I have the same bug. Did u solve the issue?

**Comment by thomasbnt** [comment]
> I have the same bug. Did u solve the issue?

Nope, I've got the issue again.

**Comment by tony1c** [comment]
So apparently I discovered that for some reason the x: 100 value (which is translate on x axis 100 from right) in the preset 'v-motion-slide-visible-once-right' causes the bug. 
I was able to solve it by specify the pixels directly in the directive, for example, like so: 
<template>
  <div
    v-motion
    :initial="{ opacity: 0, x: "100px" }"
    :visibleOnce="{ opacity: 1, x: 0 }"
  />
</template>
hope it is useful.

**Comment by tony1c** [comment]
So apparently I discovered that for some reason the x: 100 value (which is translate on x axis 100 from right) in the preset 'v-motion-slide-visible-once-right' causes the bug. 
I was able to solve it by specify the pixels directly in the directive, for example, like so: 
  <div
    v-motion
    :initial="{ opacity: 0, x: "100px" }"
    :visibleOnce="{ opacity: 1, x: 0 }"
  />
hope it is useful.

**Comment by thomasbnt** [comment]
Hello, thanks for your reply @tony1c, I tested your code, but seems not working. Same issue. 

However, I edited with `v-motion` [variants](https://motion.vueuse.org/features/variants), and works : 

```vue
<template>
<div v-motion :initial="initial" :visibleOnce="enter">
</div>
</template>
<script setup>
const initial = ref({
  x: 10,
  opacity: 0,
  visibility: "hidden",
})

const enter = ref({
  x: 0,
  opacity: 1,
  visibility: "visible",
})
</script>
```

🚀
