### ISSUE TITLE
Vitepress compatibility

### ISSUE THREAD

**Issue by davay42** [vueuse/motion#16]
Tried using v-motion directives is my vitepress project and got this error:
```
build error:  SyntaxError: Custom directive is missing corresponding SSR transform and will be ignored.
```

Seems like there's a way to make motion compatible with SSR. That could be a great feature.

**Comment by Tahul** [comment]
Hey @DeFUCC 😄 

Just install that in your repository:
`npm install --save-dev patch-vue-directive-ssr`

It should fix the issue.

Let me know if it is working, otherwise we might need to investigate a little more!

👋

**Comment by DeFUCC** [comment]
@Tahul Yeah! This helps! Thank you! 

May be it should be noted in the docs for other vitepress users.

**Comment by Tahul** [comment]
Done in https://github.com/vueuse/motion/commit/b4bcd45f793066788ad62d8e05a2b1884ea2ab89 😄

**Comment by davay42** [comment]
That's awesome!
