### ISSUE TITLE
Support v-show, to avoid missing @leave transitions

### ISSUE THREAD

**Issue by urbgimtam** [vueuse/motion#163]
At its current state, vueuse/motion only seems to work on v-if, which creates problems for @leave transitions, whenever its required to use a conditional on the component.

With v-if, a component/element is removed from the DOM as soon as the state changes. This happens before the @leave has a chance to run. 

If motion would support v-show, those issues would not happen.

**Comment by louisjrdev** [comment]
+1 I am animating a list of elements in and want to animate them out on click of a button, can't seem to trigger this if v-if unloads the elements before an animation can happen and v-show is not supported either.

**Comment by e-tho** [comment]
+1, `v-if` can have a negative impact on SEO compared to `v-show`.
