### ISSUE TITLE
How can i make a vue router leave transition?

### ISSUE THREAD

**Issue by Failip420** [vueuse/motion#20]
How can i make a vue router leave transition with this? i could only make enter animation using the docs,
I want to implement when i navigate back with vue router and get different animation?

i tried using :leave="{ opacity: 0, y: -100 }"

but it only plays enter animation when navigating back or forward

Here is the code:

`<transition>
      <router-view
        v-motion
        :initial="{ opacity: 0, y: 100 }"
        :enter="{ opacity: 1, y: 0 }"
        :leave="{ opacity: 0, y: -100 }"
      />
</transition>`

**Comment by Failip420** [comment]
Here is the code:

<transition>
      <router-view
        v-motion
        :initial="{ opacity: 0, y: 100 }"
        :enter="{ opacity: 1, y: 0 }"
        :leave="{ opacity: 0, y: -100 }"
      />
</transition>

**Comment by Tahul** [comment]
Hello @Failip420 ;

Sorry I don't have much bandwith right now, but could you make create a reproduction of what you would like to achieve so I can help you with that ?

Thanks and sorry for the late answer!

**Comment by Fanna1119** [comment]
I am also failing to resolve this.

What i have so far is.

```html

    <router-view v-slot="{ Component }">
      <transition :css="false" @leave="(el, done) => motions.cube.leave(done)">
        <component
          v-motion-pop="'cube'"
          :is="Component"
        />
      </transition>
    </router-view>


```

The first route change initiates somewhat.
I keep failing to implement the leave. After the second route change it throws:
> Cannot read property 'leave' of undefined

**Comment by Tahul** [comment]
Hey 😄

I answered with a valid code example here:
https://github.com/vueuse/motion/issues/26

I'm closing this issue as it seem to be a duplicate in its concern.

If this isn't enough, please feel free to re-open and reach me out. 😄

**Comment by NoelDeMartin** [comment]
I couldn't find the code example in #26, so in case anyone else ends up here, here's how I solved it.

It's a bit crude, but the point is that you need each page to have a unique motion name. In this case I'm using the route path, but you could use something else:

```vue
<script setup lang="ts">
import { RouterView, useRoute } from 'vue-router'
import { useMotions } from '@vueuse/motion'
import { ref, watchEffect, nextTick } from 'vue'

const route = useRoute();
const previousPath = ref();
const motions = useMotions();

watchEffect(() => {
    const newPath = route.path;

    nextTick(() => previousPath.value = newPath);
});
</script>

<template>
    <RouterView v-slot="{ Component }">
        <transition @leave="(el, done) => motions[`page-${previousPath}`].leave(done)">
            <component :is="Component" v-motion-pop="`page-${$route.path}`" />
        </transition>
    </RouterView>
</template>
```
