### ISSUE TITLE
motion component applied expired styles after component updated

### ISSUE THREAD

**Issue by ZhouY11** [vueuse/motion#202]
### System info

System(Stackblitz Website Config):
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 18.20.3 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.3 - /usr/local/bin/npm
  pnpm: 8.15.6 - /usr/local/bin/pnpm
NpmPackages:
  @vueuse/core: ^7.6.2 => 7.6.2 
  @vueuse/motion: ^2.2.3 => 2.2.3 
  vite: ^5.3.1 => 5.3.1 
  vue: ^3.2.25 => 3.2.31 

### Reproduction

Please open [Stackblitz code](https://stackblitz.com/edit/vitejs-vite-aijjcj?file=src%2FApp.vue)

### Describe the bug

Vue reapplies all styles every render, include style properties and calculated initially styles get reapplied every render.
It caused the component to apply the wrong style after triggering the update.

![屏幕截图 2024-06-18 152142](https://github.com/vueuse/motion/assets/79828139/9c9687ef-d7d4-4b0d-b2d0-1d30e75d5ee6)
![屏幕截图 2024-06-18 152551](https://github.com/vueuse/motion/assets/79828139/442131cb-77de-4de7-86aa-771bb9ed079d)

**Comment by BobbieGoede** [comment]
Resolved by #202
