### ISSUE TITLE
Nuxt 3 Error with custom directives

### ISSUE THREAD

**Issue by EngineerMonkey404** [vueuse/motion#218]
### System info

- Operating System: `Linux`
- Node Version:     `v20.16.0`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.13.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.1`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `modules`, `runtimeConfig`
- Runtime Modules:  `@vueuse/motion/nuxt@2.2.3`
- Build Modules:    `-`

### Reproduction

Create new nuxt project, install @vueuse/motion and add it to nuxt modules, then create custom directive
 runtimeConfig: {
    public: {
      motion: {
        directives: {
          'pop-bottom': {
            initial: { opacity: 0, y: 100 },
            enter: {
              opacity: 1,
              y: 0,
              transition: { duration: 400 },
            },
          }
       }
       
 
![image](https://github.com/user-attachments/assets/0be65c0d-6793-4ac0-bdb1-77222adde068)
then create something like this and you get this
![image](https://github.com/user-attachments/assets/fb8d108d-7da0-4141-b943-5ce87663e9cf)

### Describe the bug

Cannot use custom animation in Nuxt3 with vueuse/motions directive

**Comment by hajiskyy** [comment]
Issue seems to be happening here https://github.com/vueuse/motion/blob/eb7c01de524be8fef787148ee146aa780dd3692d/src/directive/index.ts#L24

it seems that we are receiving a vue ref object and so the `stucturedClone` fails. I'm guessing it's a simple fix by using a `toRaw(variants)` on that line

**Comment by hajiskyy** [comment]
Not sure who to tag here but i have an open PR that potentially fixes this issue here https://github.com/vueuse/motion/pull/221

@Tahul @BobbieGoede

**Comment by BobbieGoede** [comment]
This should be resolved thanks to @hajiskyy's contribution! You can install a preview release containing the fix like so `npm i https://pkg.pr.new/@vueuse/motion@221` until a new full release has been published.
