### ISSUE TITLE
[BUG] `useSpring` won't work properly when initial value is 0

### ISSUE THREAD

**Issue by yaquawa** [vueuse/motion#23]
Reproduce link:
https://codesandbox.io/s/vueusemotion-forked-9zzt7?file=/src/components/Person.vue

Steps to reproduce
1. click "to 100"
2. click "to 0"
3. click "to 100" again

You'll notice that the first time when you click the  "to 100" button, the animation won't take effect.
But if you set the initial value to anything number except for `0`, it works...

**Comment by Tahul** [comment]
Hey, thank you for this issue!

It should be resolved in 1.6.0.

Could you try it out? 😄

**Comment by yaquawa** [comment]
Thanks! it works fine now!!
