### ISSUE TITLE
Relative motion properties

### ISSUE THREAD

**Issue by giancarllorojas** [vueuse/motion#24]
First, this is a great library, thanks to everyone who contributed to it.

I'm trying to use it with relative(percentage) properties like this:
```
<div
    v-motion
    :initial="{ x: '0%' }"
    :enter="{ x: '60%' }"
/>
```

And I'm getting the "TypeError: v.match is not a function" error.

Is this not supported? Thanks!

**Comment by Rigo-m** [comment]
I don't know why this is here since June 2021...
Btw, you can leverage popmotion string parsing capabilities and write this code, which works:
```html
<div
  v-motion
  :initial="{ transform: 'translateX(0%)' }"
  :enter="{ transform: 'translateX(60%)'}"
/>
```

**Comment by Rigo-m** [comment]
@antfu this is a very much needed feature, hinders a lot of responsive animations. There should be a clear stand on this issue, when you have 5 minutes could you take a look at this? Thanks 😄 ❤️

**Comment by jjjuulliiaann** [comment]
Would be great to have percentage values supported in style properties! :)
