### ISSUE TITLE
Updating to vite >= 6.0.0 causes error

### ISSUE THREAD

**Issue by matteoscaramuzza** [vueuse/motion#245]
### System info

```
  System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 546.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /usr/local/bin/npm
    pnpm: 9.12.3 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
  npmPackages:
    @vueuse/motion: 2.2.6 => 2.2.6 
    vite: ^6.0.1 => 6.0.1 
    vue: ^3.5.13 => 3.5.13
```

### Reproduction

When updating vite to >= 6.0.0, when I launch my storybook instance this error is thrown.

`TypeError: Cannot destructure property '__extends' of 'import_tslib.default' as it is undefined.
    at http://localhost:6007/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/@vueuse_motion.js?v=fe8ad6fc:891:3`

Removing this row: 

`vue.use(MotionPlugin);`

the error disappears, so I think the problem is within the library

### Describe the bug

Cannot destructure property '__extends' of 'import_tslib.default' as it is undefined.

**Comment by matteoscaramuzza** [comment]
I think the problem was fixed by vite latest version (v6.0.3).

**Comment by DhtIsCoding** [comment]
it's not fixed. I got the same exception when use echarts

**Comment by BobbieGoede** [comment]
@DhtIsCoding 
If you could provide a minimal reproduction I can investigate your issue 🙏
