### ISSUE TITLE
Can I load the animation only the first time it's visible

### ISSUE THREAD

**Issue by Jonathanqjs** [vueuse/motion#25]

**Comment by Tahul** [comment]
Could you add a little bit more context to that question?

You can do what the title asks by adding a onComplete listener and creating a ref tracking it combined with an intersection observer maybe?

Using [:visible](https://motion.vueuse.org/directive-usage.html#your-first-v-motion) should do the trick though.

I'm closing this, feel free to re-open if you have any more questions.

**Comment by aaronransley** [comment]
@Tahul I had the same question. I think the desired behavior is "trigger the :visible variant only the first time an element enters the viewport", rather than the default behavior which seems to rewind the animation and replay it each time the element re-enters the viewport.
