### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by altinselimi** [vueuse/motion#27]
This is the reproduction repo:
https://codesandbox.io/s/great-montalcini-ni16i

Go ahead and start allocation sampling in the devtools memory tab. Here is a screenshot:
![image](https://user-images.githubusercontent.com/10469822/125338605-b516ef00-e350-11eb-8df1-a4d6b05aa252.png)

This was hands down the trickiest memory leak I ever managed to find.

**Comment by Tahul** [comment]
@altinselimi ; maybe we could collaborate on trying to solve this problem ?

**Comment by Tahul** [comment]
I've tried to reach your on Twitter concerning this issue. 😄

I will need more context about this one if you want me to solve that, I've been using @vueuse/motion in various projects and would love to fix any memory leak.
