### ISSUE TITLE
Vue 3 Issue - Might be a webpack issue not sure?

### ISSUE THREAD

**Issue by vivalahurricane** [vueuse/motion#28]
Hi everyone, 
I'm sorry if this is not a issue with vueuse/motion and is a webpack issue, but I'm not sure. 
This is the error that I keep getting: 
     INFO  Starting development server...
    98% after emitting CopyPlugin
    
     ERROR  Failed to compile with 1 error        1:30:37 PM
    
     error  in ./node_modules/@vueuse/motion/dist/index.esm-bundler.js
    
    Module parse failed: Unexpected token (131:18)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |  */
    | class SubscriptionManager {
    >     subscriptions = new Set();
    |     add(handler) {
    |         this.subscriptions.add(handler);
    
     @ ./src/main.js 8:0-46 27:61-73
     @ multi (webpack)-dev-server/client?http://10.0.0.105:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

I've uninstalled webpack and reinstalled, cleared the cache, and it's still not working! Thank you to anyone who can help!

**Comment by patrickdaley** [comment]
Same here with Vue 2.

**Comment by galaxyblur** [comment]
Also seeing this issue on Vue 2 (Nuxt & nuxt-use-motion)

**Comment by Tahul** [comment]
Hello guys 😄

Sorry for that, could you all try 2.0.0-beta.1 ?

Thanks for the feedback 🙏

**Comment by Tahul** [comment]
@vivalahurricane ; @patrickdaley ; @Elliot-Alexander ; @galaxyblur 😄

Could you tell me if it works for you ?

I tried it myself with Nuxt & Vite projects, work on both sides.
