### ISSUE TITLE
Could we make *-visible directives work when the element is visible from the start?

### ISSUE THREAD

**Issue by xstevenyung** [vueuse/motion#29]
Hello,

As said in the title, In some cases, when doing responsive landing page design (e.g. 15" laptop screen vs 4k screen), it's not really possible to predict 100% of the time when an element will be visible on the first load.

In the cases when a `*-visible` directive is visible on the first load, the animation never trigger making the element invisible.

I made a repo to illustrate: https://github.com/xstevenyung/v-motion-visible-issue

I could work on a PR if this is something that make sense to change.

Cheers and thanks for your work !

**Comment by Tahul** [comment]
Hey Steven, thank you for your issue!

That seem like great idea!

I would happily review any PR that you submit, please let me know if you need anything concerning the code itself. 😄

**Comment by Blastius** [comment]
I have the same issue, some elements are already in the viewport at page load, but not visible initially. Only after scrolling down and back up to those elements will show them. Is a solution being worked on or does this not have a priority?

**Comment by rashidpathiyil** [comment]
Same issue

**Comment by JonHerbert** [comment]
Same issue, thanks!

**Comment by maddybo** [comment]
Same issue :C

**Comment by gl-ruslan-honchar** [comment]
Same issue ((

**Comment by maddybo** [comment]
@Tahul

**Comment by Qazzquimby** [comment]
Are people using some kind of workaround?
Given [the proposed fix](https://github.com/vueuse/motion/pull/33/files#) isn't going anywhere, maybe it could be monkeypatched in?

**Comment by sainf** [comment]
@Qazzquimby the idea on [proposed fix](https://github.com/vueuse/motion/pull/33/files#) works fine.

I'm having problems with my local build, so I won't make a PR. @Tahul , please check:
[Adding nextTick to visible & visibleOne](https://github.com/sainf/motion/commit/96b8c17fcf82166275c18c06b12588e2b9016e29)

But for know I'm using the solution with Presets and Variants, hacking the node_modules

**Comment by stonega** [comment]
Same issue

**Comment by MathiasOxholm** [comment]
This is still an issue :/

**Comment by kaypappi** [comment]
This is still a huge issue. And its killing the awesomeness of this package. is there a workaround?

**Comment by jordangunther** [comment]
Same issue
