### ISSUE TITLE
Suggestion: Reduce the usage of bold texts in docs

### ISSUE THREAD

**Issue by peter50216** [vueuse/motion#32]
When reading the docs I'm continuously distracted by the (seemly random) **bold** texts all over the places. I feel it would be better to remove most of them, and only leaves the few really important ones.

**Comment by Tahul** [comment]
Hello @peter50216 ; thanks for the suggestion!

This has been fixed in this commit: b72600f923e318f5a87b412c4bb211ed7912e8d7

If you see any spot in which it seem to be missing, please tell me!
