### ISSUE TITLE
[question] What vueuse/layout will provide

### ISSUE THREAD

**Issue by jd-0001** [vueuse/motion#36]
Hi,

I just show that you have idea regarding `vueuse/layout` in your roadmap.

With curiosity, I want to ask what that package will provide.

**Comment by Tahul** [comment]
Hello @jd-0001 ;

What I would like to achieve with a `vueuse/layout` project if I had time for it would be to have the same features offered by Framer Motion in terms of layout animation.

You can see examples there:
https://www.framer.com/docs/animate-shared-layout
https://www.framer.com/docs/animate-shared-layout/#animate-between-components
