### ISSUE TITLE
`visible` lifecycle variant is flickering when element is no more intersecting

### ISSUE THREAD

**Issue by rufusmai** [vueuse/motion#38]
If an element goes out of the viewport, the fade out animation starts. 
This brings the element back in to the viewport and may cause a fade in animation.

Maybe a cooldown should be added to the `useIntersectionObserver` usage, [here](https://github.com/vueuse/motion/blob/0c7a97626710bc106b865e1e5564a5f5c1567aef/src/features/visibilityHooks.ts#L15)?

**Comment by Tahul** [comment]
Hello @rufusmai ;

Could you please provide a reproduction to this issue?

Thanks a lot 🙏

**Comment by Tahul** [comment]
I think this is somehow related to https://github.com/vueuse/motion/issues/63

I am closing this issue as no reproduction has been provided, feel free to re-open if you still have the issue!

**Comment by rufusmai** [comment]
Hello, I'm not sure how #63 is related to that. But I created a reproduction:
https://stackblitz.com/edit/vue-wsbrnv?file=src/App.vue

First, the image is not showing up after page load, even though it's in the viewport.
It works after scrolling down and up again.
Second, if you scroll down again, before the image is hiding, it starts to flicker.
