### ISSUE TITLE
Main Entrypoint not recognized as a valid entrypoint

### ISSUE THREAD

**Issue by leonardotessaroalves** [vueuse/motion#39]
`Error
Cannot find module '@vueuse/motion/dist/index.js'. Please verify that the package.json has a valid "main" entry`

In package.json
"main": "./index.js" >>> "main": "./index.cjs"

**Comment by Tahul** [comment]
I cannot reproduce this issue.

I'm closing this as there is no reproduction, feel free to reopen.
