### ISSUE TITLE
Declare sideEffects in package.json to know size of exports

### ISSUE THREAD

**Issue by santicros** [vueuse/motion#4]
Hi Yaël,

First thanks for your package, it's sooo great to have a solid alternative of Framer-motion in Vue! ;)

One thing I was checking was the size of the package in Bundlephobia (https://bundlephobia.com/result?p=@vueuse/motion) and I saw that Export Analysis isn't shown because sideEffects hasn't been declared. I'm not 100% sure if the package meets the requirements to be sideEffects free, but I think so (here is a great explanation https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free).

If it meets the requirements, with that change, users could better understand the size of each part of the package 💯 

Thanks again for your work!!!!

**Comment by Tahul** [comment]
Thank you a lot for your advice Santicros.

As Framer Motion, we are including Popmotion as a dependency and I think it should be mentioned in package.json as you say.

I'll do that soon.

**Comment by santicros** [comment]
I've checked and Framer Motion has sideEffects: false -> https://github.com/framer/motion/blob/main/package.json#L11
VueUse Core too --> https://github.com/vueuse/vueuse/blob/main/packages/core/package.json#L10

So I think it's safe to put sideEffects: false as my PR :)

**Comment by Tahul** [comment]
Thank you a lot @santicros, it has been merged!
