### ISSUE TITLE
feat(docs): algolia doc search

### ISSUE THREAD

**Issue by Fanna1119** [vueuse/motion#45]
Thank you for the awesome library!
I just wanted to ask if it would be possible to adapt the docs to have a search. There is so much going on in the library.  Maybe also more practical examples?

**Comment by Tahul** [comment]
Hello Fanna :)

Could you tell me which kind of examples you would like to see?

Also this is an excellent idea for Algolia.

Actually I am working on new version of Nuxt Content and Nuxt Docs Theme and I am waiting for this project release to rebuild and put efforts on this library documentation and implementation. :)
