### ISSUE TITLE
difference between useSpring and useMotion? And their use cases?

### ISSUE THREAD

**Issue by Fanna1119** [vueuse/motion#46]
Looking at the docs example.
https://motion.vueuse.org/api/use-spring.html#example
it uses `scale` I can't get the example to work. I am trying to toggle between 2 values.

```js

<script setup>
import { ref } from "vue";
import { useSpring } from "@vueuse/motion";

const active = ref(false);
const target = ref();

const { set } = useSpring(target, {
  damping: 50,
  stiffness: 400,
  restDelta: 1,
  mass: 1,
});


const toggle = () => {
  active.value = !active.value;
  if (active.value) {
    set({
      x: 20,
    });
  } else {
    set({
      x: 0,
    });
  }
};
</script>

<template>
  <div class="outer" @click="toggle">
    <div class="toggle" ref="target"></div>
  </div>
</template>


<style>
.outer {
  background: rgb(192, 192, 192);
  border-radius: 3em;
  width: 50px;
  height: 20px;
}

.toggle {
  background: rgb(255, 255, 255);
  border-radius: 5em;
  transition: all 0.5s;
  width: 20px;
  height: 20px;
  box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.5);
}
</style>

```

Update:

after some more digging i figured i can use the `apply`. from usemotion

however i am bit confused on the difference between

```js
const target = ref();
const { apply } = useMotion(target);
```

and 

```js
const target = ref()

const { motionProperties } = useMotionProperties(target)

const { apply } = useMotionControls(motionProperties)
```

**Comment by Tahul** [comment]
"It skips the [Variants](https://motion.vueuse.org/variants.html) system, allowing it to be as performant as using Popmotion natively, but with a nicer API to play with Vue refs."

From this page:
https://motion.vueuse.org/api/use-spring.html

The benefits of not using  useMotion is a pure performance benefit.

It just skips various things like checking for event listeners, variants system, and others.

It is made to manipulate your styling from a regular object in a easy way.
