### ISSUE TITLE
When it is not hovering, it cannot be restored to the previous state

### ISSUE THREAD

**Issue by han1548772930** [vueuse/motion#55]

**Comment by han1548772930** [comment]
> _未提供说明。_

**Comment by han1548772930** [comment]
<img width="309" alt="121" src="https://user-images.githubusercontent.com/83765419/159044754-6723fd0e-0b1c-43e5-975d-ecc7384ea824.png">

**Comment by Tahul** [comment]
You need to add scale to the `:enter` key of your transition!

In your example, scale won't be reverted as it has  no value set fallback state.

As you communicate in Chinese, I tried to translate the text above in it:

您需要在过渡的 `:enter` 键中添加比例！

在您的示例中，规模不会被恢复，因为它没有值设置后备状态。

**Comment by han1548772930** [comment]
> 您需要为`:enter`过渡的关键添加比例！
> 
> 在您的示例中，比例不会恢复，因为它没有值设置后备状态。
> 
> 当你用中文交流时，我试着翻译上面的文字：
> 
> 您需要在过渡的 `:enter` 键中添加比例！
> 
> 在您的示例中，规模不会被恢复，因为它没有值设置后备状态。

thanks

**Comment by han1548772930** [comment]
thanks
