### ISSUE TITLE
SSR doesn't seem to work as intended

### ISSUE THREAD

**Issue by cerinoligutom** [vueuse/motion#58]
As per [docs on SSR Support section](https://motion.vueuse.org/nuxt.html#ssr-support), there are 2 options that should work:

```vue
<template>
  <div
    v-motion="{
      initial: {
        y: 100,
        opacity: 0
      },
      enter: {
        y: 0,
        opacity: 1
      }
    }"
  >
    Hello
  </div>

  <!-- OR -->

  <div
    v-motion
    :initial="initial"
    :enter="enter"
  >
    Hello
  </div>
</template>

<script setup>
const initial = ref({
  y: 100,
  opacity: 0,
})

const enter = ref({
  y: 0,
  opacity: 1,
})
</script>
```

The **1st option** where we put a stringified object as value on the `v-motion` directive **works**. However, the **2nd option** where we bind variables to `:initial` and `:enter` **doesn't work**. The latter shows the elements normally and then the animations get applied afterwards. See gif below:

![issue demo](https://cdn.discordapp.com/attachments/932164997046489178/958831584746799174/chrome_2022_03_31_044332415.gif)

That said, the [composable usage](https://motion.vueuse.org/composable-usage.html) isn't working either. It seems to behave as if the variables only gets bound [on mounted](https://vuejs.org/api/composition-api-lifecycle.html#onmounted) but that doesn't work for SSR.

**Additional Context:**

This works and I'm getting away with this for the meantime:

```vue
<template>
  <div v-motion="motion">Hello</div>
</template>

<script setup>
const motion = {
  initial: {
    y: 100,
    opacity: 0
  },
  enter: {
    y: 0,
    opacity: 1
  }
};
</script>
```

**Versions used:**
```json
{
  "nuxt3": "latest",
  "@vueuse/motion": "2.0.0-beta.18"
}
```

**Comment by Tahul** [comment]
Could you try `@vueuse/motion@2.0.0-beta.22` ?

Sorry for the last answer, this one is now tracked in #81

**Comment by cerino-ligutom** [comment]
Hi @Tahul , thanks for getting back on this. Not using it anymore on my SSR projects as the template got unwieldy with all the animations but would be happy to assist.

I think it's still happening. Check this [repro on stackblitz](https://stackblitz.com/edit/github-iahpv4?file=app.vue) and refresh the web view.

![demo_issue](https://i.imgur.com/u16HePc.gif)

**Comment by BobbieGoede** [comment]
I'm not sure if we can make SSR work using the `v-motion` directive with separate variant props (e.g. `:initial`, `:enter`), we can't retrieve the separate props during SSR as the node does not exist yet 🤔.

The usage of passing the variants directly to `v-motion` allows us to correctly set the node's `style` during SSR, no existing node is required as the directive is provided all the necessary information.

I think we should probably mention this in the docs, I'll look into the (undocumented?) `<Motion>` component as well SSR should work without issues for components using the prop usage.

**Comment by BobbieGoede** [comment]
With `2.2.0` released you can now use the `<Motion>` component which will work better for SSR projects, I have edited your reproduction to demonstrate [here](https://stackblitz.com/edit/github-iahpv4-klpnau?file=app.vue).

Unfortunately we're having some issues deploying the updated docs which describes the `<Motion>` component so I'll add a link when that is resolved.

I'll close this issue now, if you specifically prefer the `v-motion` directive and would like SSR to work with that we could open a separate issue, the solution for that will be a bit more complicated but it's not impossible. Let me know if you have any questions!

**Comment by BobbieGoede** [comment]
Docs have been updated, you can find more about the components here https://motion.vueuse.org/features/components!
