### ISSUE TITLE
[ NUXT 2 - Bridge ] - Package subpath './nuxt' is not defined by "exports" in package.json

### ISSUE THREAD

**Issue by Beethoven** [vueuse/motion#59]
Package subpath './nuxt' is not defined by "exports" in /node_modules/@vueuse/motion/package.json

**Comment by iojanis** [comment]
Same here

**Comment by ndom91** [comment]
Having this issue as well with a greenfield Nuxt3 project. Installing the "latest" `2.0.0-beta.18` fixed it :+1:

**Comment by cesswhite** [comment]
Agree with this solution  `"@vueuse/motion": "^2.0.0-beta.18"` 👍

**Comment by hamedbaatour** [comment]
anyone having issues installing `@vueuse/motion` with Nuxt 3 try the following

1. create a `.npmrc` in the root of your project
2. add the following to it:
```
auto-install-peers=true
legacy-peer-deps=true
```
3. make sure your use the latest `beta` version in your `package.json` file which is `"^2.0.0-beta.18"` at the time of writing this.
```
  "dependencies": {
    "@vueuse/motion": "beta"
  }
  ```
  4. run `npm i` to install
  
  
  everything should work normally and you should not get any errors at this point. hope this helps!

**Comment by Tahul** [comment]
Hey here, really sorry about the late answer.

This won't happen again.

Could you try `@vueuse/motion@2.0.0-beta.22` ?

Thank you a lot for providing workarounds in the meantime, @iojanis and @hamedbaatour. 💚

**Comment by Bryanoxx** [comment]
Hi ! 

I just had the same bug by installing the `latest` tag version on Nuxt 3.0.0-rc.9, and by upgrading to the `beta` tag version: everything went well and the library now works perfectly 🔥

**Comment by Tahul** [comment]
Closing this as it seem resolved!

Thank you so much for the quick feedback!

Feel free to re-open!
