### ISSUE TITLE
Animations not completing in Chromium browsers

### ISSUE THREAD

**Issue by cwilvx** [vueuse/motion#71]
I'm using v-motion animations on a Vue-3 application and the animations are failing on chromium browsers. I've tested my app on Chrome, Vivaldi and Brave and I'm getting the same result. Everything seems to be working fine on Firefox.

For example, the `v-motion-slide-visible-left` preset does not work on chrome but works fine on firefox.

### Firefox
https://user-images.githubusercontent.com/48554537/173181349-14fe2f6a-a9f5-4e9b-94fc-5ed3dbe0796d.mp4

### Chrome
https://user-images.githubusercontent.com/48554537/173181364-f0109c58-6bbd-436a-b034-0ef6cace546c.mp4

---
Inspecting the DOM I found that the div with the preset had this style attached to it.
```css
transform: translate3d(-100px, 0px, 0px); opacity: 0;
```
![Screenshot from 2022-06-11 12-07-11](https://user-images.githubusercontent.com/48554537/173181488-048f2314-5523-4c17-ae11-9d48dd67c1cb.png)

Why is this happening? How can I fix it?

**Comment by Applicafroguy** [comment]
Did you find any solution, All nimation work fine in firefox, but in chrome they sometimes work

**Comment by JeremyMees** [comment]
I also have the same problem the animation doesn't play when te page is loaded only when i scroll down and back up agian

**Comment by breizhwave** [comment]
Hi, the initial animation does not work on chrome , firefox OK (hero text)
https://e1xowy.csb.app/

**Comment by JeremyMees** [comment]
> Hi, the initial animation does not work on chrome , firefox OK (hero text) https://e1xowy.csb.app/

I have the same problem but are you also server side rendering your site?
My components that are SSR work perfectly but when i await data in them they break.
So i think the animations isn't set correct when the components aren't directly visible for the client

**Comment by AntonyZ89** [comment]
Same here :(

**Comment by BobbieGoede** [comment]
This issue is likely fixed by https://github.com/vueuse/motion/pull/171 which is now included in the latest release v2.1.0, but without a reproduction I'm unable to confirm this, can someone check if this issue has been resolved after installing the latest version?
