### ISSUE TITLE
add delay to presets animation

### ISSUE THREAD

**Issue by Chandler-Zhu** [vueuse/motion#74]
Is there a way to add delay to the preset animation ? The doc didn't mention this, if you plan to add this in the future, I think this syntax would look good:
`<div v-motion-slide-right  :delay="500" />`
The feature I wanted to add to my app is to `v-for` loop through an array and give each item a different `delay` based on their index, if this is possible with the current version please let me know how, thanks

**Comment by TheMangoTrain** [comment]
> The feature I wanted to add to my app is to `v-for` loop through an array and give each item a different `delay` based on their index, if this is possible with the current version please let me know how, thanks

This is essentially staggered animation, and although the way you describe may be possible with a convenient preset-adjustment we're all talking about, I think that staggered-anim is still better served by using custom motions triggered by Vue animation hooks, all wrapped in a `<TransitionGroup>`. This is exactly what I've done using this library for staggered list animations.

**Comment by innocenzi** [comment]
I think this should be considered a bug, it's very confusing that the `:delay` is applied to all motion directives within a `v-for` and not to individual elements:

```vue
<div v-for="i in 5" :key="i">
	<div
		v-motion-slide-visible-left
		:delay="100 * i"
	/>
</div>
```
