### ISSUE TITLE
How to create sequence enter div animation one by one

### ISSUE THREAD

**Issue by myomyintaung1411** [vueuse/motion#84]

**Comment by BobbieGoede** [comment]
You can create a staggered div animation by adding delays to each div, here's an example:

```vue
<div>
    <img
      v-for="index in 5"
      :key="index"
      v-motion
      :initial="{ scale: 0, opacity: 0 }"
      :visible-once="{ scale: 1, opacity: 1 }"
      :delay="index * 200"
    />
</div>
```

Note the `:delay="index * 200"` which adds a longer delay for each following div, I've also created a demonstration [here](https://stackblitz.com/edit/vitejs-vite-hnhza2?file=src%2FApp.vue). 

Closing this, let me know if you have any questions!
