### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by santicros** [vueuse/motion#9]
Hi @Tahul! I'm here again testing it haha 💖

My first problem was that the demo component on the website and README isn't working as is.
First, the code I'm talking about is (I've just added 3 lines of CSS):

``` vue
<template>
  <div
    id="test-box"
    v-motion="'smoothestDiv'"
    :initial="{
      opacity: 0,
      y: 100,
    }"
    :enter="{
      opacity: 1,
      y: 0,
    }"
  />
</template>

<script setup>
import { useMotions } from "@vueuse/motion";

// Get access to motion instance using useMotions
const { smoothestDiv } = useMotions();

// From smoothest div to biggest div real quick 😎
smoothestDiv.apply({ scale: 4 });
</script>

<style>
#test-box {
  width: 20rem;
  height: 20rem;
  background: red;
}
</style>

```
1. The App breaks because it's not finding smoothestDiv and so can't apply:
``` console
[Vue warn]: Unhandled error during execution of setup function 
  at <App>
  
App.vue:23 Uncaught TypeError: Cannot read property 'apply' of undefined
    at setup (App.vue:23)
```
2. So then I added a check, so we don't apply if the code is smoothestDiv is undefined:
``` js
smoothestDiv?.apply({ scale: 4 });
```
The thing is it's always undefined. I think we should do something like:
```js
onMounted(() => {
  smoothestDiv?.apply({ scale: 4 });
});
```
3. Yet it's not working! hahahah I think it's because when desctructuring motions from useMotions() we are loosing reactivity, so if we use motions.smoothestDiv everything works.

So here's the working demo:
``` vue
<template>
  <div
    id="test-box"
    v-motion="'smoothestDiv'"
    :initial="{
      opacity: 0,
      y: 100,
    }"
    :enter="{
      opacity: 1,
      y: 0,
    }"
  />
</template>

<script setup>
import { useMotions } from "@vueuse/motion";
import { onMounted } from "vue";

// Get access to motion instance using useMotions
const motions = useMotions();

// From smoothest div to biggest div real quick 😎
onMounted(() => {
  motions?.smoothestDiv?.apply({ scale: 4 });
});
</script>

<style>
#test-box {
  width: 20rem;
  height: 20rem;
  background: red;
}
</style>

```

Let me know if it should be like that! Thanks ;)

**Comment by Tahul** [comment]
Hey @santicros ;

You're totally right, that example is not so correct.

Instead of showcasing so much content in a "Quick Start" example, I simplified it to keep the <template> part only.

Thank you for your feedback. 🤗
