### ISSUE TITLE
`visible` lifecycle variant is flickering when element is no more intersecting

### ISSUE THREAD

**Issue by rufusmai** [vueuse/motion#94]
(I'm reopening this issue from #38 because I'm not sure if this issue is related to #63)

If an element goes out of the viewport, the fade out animation starts.
This brings the element back in to the viewport and apparently causes a fade in animation.

Here is a reproduction: https://stackblitz.com/edit/vue-wsbrnv?file=src/App.vue

First, the image is not showing up after page load, even though it's in the viewport.
It works after scrolling down and up again.
Second, if you scroll down again, before the image is hiding, it starts to flicker.

**Comment by aonghas** [comment]
Same with me!

**Comment by manch1915** [comment]
Same with me

**Comment by LePulsar** [comment]
Same for me. Does anyone know how to handle this?

**Comment by MIN202299** [comment]
same with me

**Comment by BobbieGoede** [comment]
This is resolved in the v2.1.0!
