### ISSUE TITLE
npm add @vueuse/motion

### ISSUE THREAD

**Issue by burak-akdogan** [vueuse/motion#97]
![image](https://user-images.githubusercontent.com/66314810/210956230-eb2195e9-da88-4736-a3ab-1bb42d5f84cf.png)

**Comment by lerayj** [comment]
Install the `2.0.0-beta.25` version.

`npm install --save @vueuse/motion@2.0.0-beta.25`

or add `"@vueuse/motion": "2.0.0-beta.25"` to your package.json then npm install again.
