### ISSUE TITLE
the Target element doesn't appear after adding :visible directive

### ISSUE THREAD

**Issue by MOUAAD-NASSIH** [vueuse/motion#98]
I faced one problem while using this animations that is when i refresh the page my target element which is already visible disappears from the page.

Here is The code below.

`<template>`
 ` <!-- this is my target   -->`
  ```
<div
    v-motion
    :initial="{ opacity: 0, y: 100 }"
    :visible="{ opacity: 1, y: 0 }"
    :delay="200"
  >
```
    `<a href="https://vuejs.org/" target="_blank">`
      `<img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />`
    `</a>`
  `</div>`
`</template>`

if i switched the visible directive with the enter directive it works fine .
here is  a reproduction in the stackblitz environment link : https://stackblitz.com/edit/vitejs-vite-nbjert?file=src%2Fmain.js,src%2FApp.vue&terminal=dev

**Comment by aonghas** [comment]
Same thing with me!
